#!/bin/bash
sed '/\n/!s/[0-9.]\+/\n&\n/;/^\([0-9]\{1,3\}\.\)\{3\}[1]\{1\}\n/P;D' namefile.json >> text
nmap -iL text -sn -n -oG - | awk -F" " '!/#/ {print $2}' >> text.txt
export SSHPASS=password
while read line
do
        sshpass -e ssh name@"$line" "system identity print; ip address print" >> text1.txt < /dev/null
done < "$1"
